databases:
  - name: horilla-db
    plan: free
    databaseName: horilla
    user: horilla

services:
  - type: web
    name: horilla
    plan: free
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn horilla.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://horilla.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: horilla-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.10.0"
